version: "1.0"
services:
  api_tw:
    build: .
    ports:
      - "4321:4321"
    links:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin